# -*- coding: utf-8 -*-
"""hw2-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14jSKtbmBEfmQfyPG2Uqmdqc1vxgaD_Cj
"""

def collect_personal_data():
    # 收集個人資料
    name = input("請輸入您的姓名：")
    age = int(input("請輸入您的年齡："))
    height = float(input("請輸入您的身高（米）："))
    favorite_color = input("請輸入您喜愛的顏色：")

    # 創建字典存儲資料
    personal_data = {
        '姓名': name,
        '年齡': age,
        '身高': height,
        '喜愛的顏色': favorite_color
    }

    return personal_data

def format_personal_data(personal_data):
    # 格式化個人資料摘要
    summary = "{name}，{age}歲，身高{height}米，喜愛的顏色是{color}。".format(
        name=personal_data['姓名'],
        age=personal_data['年齡'],
        height=personal_data['身高'],
        color=personal_data['喜愛的顏色']
    )
    return summary

def main():
    # 收集個人資料
    personal_data = collect_personal_data()

    # 格式化個人資料並輸出摘要
    summary = format_personal_data(personal_data)
    print(summary)

if __name__ == "__main__":
    main()