# -*- coding: utf-8 -*-
"""hw2-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SOHsH0N17mfDVQy66XXwbXx0nNVBm5w_
"""

import math
r=float(input("請輸入圓的半徑r:"))

p=2*math.pi*r  #圓的周長
s=math.pi*r**2 #圓的面積
print("圓的周長是：",p)
print("圓的面積是：",s)